# Настройки сайта
title: Ваш заголовок
description: Описание вашего сайта
theme: jekyll-theme-minimal # Тема вашего сайта

# Настройки URL-адресов
baseurl: "" # Пустая строка для основного URL-адреса сайта
url: "https://ваш_сайт.github.io" # Замените ваш_сайт на имя вашего репозитория

# Настройки временной зоны
timezone: Europe/Moscow # Часовой пояс вашего сайта

# Настройки для GitHub Pages
remote_theme: null # Отключение использования удаленной темы, если вы хотите использовать локальную тему
